/**
 * Content generator script
 * Reads all post READMEs and examples, generates a content data file
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const postsDir = path.join(__dirname, '../../posts');
const outputFile = path.join(__dirname, '../src/data/postsContent.js');

function getPostFolders() {
    return fs.readdirSync(postsDir)
        .filter(f => fs.statSync(path.join(postsDir, f)).isDirectory())
        .sort();
}

function readPostContent(folder) {
    const postPath = path.join(postsDir, folder);
    const readmePath = path.join(postPath, 'README.md');
    const examplesDir = path.join(postPath, 'examples');

    let readme = '';
    if (fs.existsSync(readmePath)) {
        readme = fs.readFileSync(readmePath, 'utf8');
    }

    const examples = [];
    if (fs.existsSync(examplesDir)) {
        const files = fs.readdirSync(examplesDir).filter(f => f.endsWith('.py')).sort();
        for (const file of files) {
            const content = fs.readFileSync(path.join(examplesDir, file), 'utf8');
            examples.push({ name: file, content });
        }
    }

    // Extract post number from folder name
    const match = folder.match(/^(\d+)-/);
    const postId = match ? parseInt(match[1]) : 0;

    return { postId, slug: folder, readme, examples };
}

function generateOutput() {
    const folders = getPostFolders();
    const posts = folders.map(readPostContent);

    let output = '// Auto-generated file - do not edit directly\n';
    output += '// Generated by scripts/generate-content.js\n\n';
    output += 'export const postsContent = {\n';

    for (const post of posts) {
        output += `  ${post.postId}: {\n`;
        output += `    slug: ${JSON.stringify(post.slug)},\n`;
        output += `    readme: ${JSON.stringify(post.readme)},\n`;
        output += `    examples: [\n`;
        for (const ex of post.examples) {
            output += `      { name: ${JSON.stringify(ex.name)}, content: ${JSON.stringify(ex.content)} },\n`;
        }
        output += `    ],\n`;
        output += `  },\n`;
    }

    output += '};\n';

    fs.writeFileSync(outputFile, output);
    console.log(`Generated content for ${posts.length} posts to ${outputFile}`);
}

generateOutput();
